// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4KjspjtHgSQgpMtZ0ZmulGSkrKXwcqNs',
    appId: '1:830716909174:web:8e4942d8009cc40406b157',
    messagingSenderId: '830716909174',
    projectId: 'beestore-selinkarpuzcu',
    authDomain: 'beestore-selinkarpuzcu.firebaseapp.com',
    storageBucket: 'beestore-selinkarpuzcu.appspot.com',
    measurementId: 'G-N3ZJLRVZ18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV8tO9TYjYjVHhThJm0nA7roLMJ4_GRKM',
    appId: '1:830716909174:android:c8ce03bac550a7bf06b157',
    messagingSenderId: '830716909174',
    projectId: 'beestore-selinkarpuzcu',
    storageBucket: 'beestore-selinkarpuzcu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBacPeUDoxplXQzfa9nhyigl8CJLx0u0QA',
    appId: '1:830716909174:ios:f7aaa73608a9dab806b157',
    messagingSenderId: '830716909174',
    projectId: 'beestore-selinkarpuzcu',
    storageBucket: 'beestore-selinkarpuzcu.appspot.com',
    iosBundleId: 'com.example.beeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBacPeUDoxplXQzfa9nhyigl8CJLx0u0QA',
    appId: '1:830716909174:ios:13e4413b37bbd85606b157',
    messagingSenderId: '830716909174',
    projectId: 'beestore-selinkarpuzcu',
    storageBucket: 'beestore-selinkarpuzcu.appspot.com',
    iosBundleId: 'com.example.beeStore.RunnerTests',
  );
}
